# show all available tasks
_default:
  @just --list


# setup dev environment for language
setup-devenv-for language nix_type="flake":
  @just copy-justfile-template {{language}} .
  @just copy-{{nix_type}}-template {{language}} .
  @just enable-direnv-for-{{nix_type}}

# enable direnv for nixshell
enable-direnv-for-nixshell:
  echo "use nix" >> .envrc && direnv allow

# enable direnv for flake
enable-direnv-for-flake:
  echo "use flake" >> .envrc && direnv allow


# show all justfile templates
[no-cd]
show-all-justfile-templates:
  ls -a ~/_justfile_templates/

# copy justfile template to target directory
[no-cd]
copy-justfile-template template_name target_directory:
  cp ~./_justfile_templates/{{template_name}} {{target_directory}}/justfile


# show all flake templates
[no-cd]
show-all-flake-templates:
  ls -a ~/_flake_templates/

# copy flake template to target directory
[no-cd]
copy-flake-template template_name target_directory:
  cp ~./_flake_templates/{{template_name}} {{target_directory}}/flake.nix


# show all nix-shell templates
[no-cd]
show-all-nixshell-templates:
  ls -a ~/_nixshell_templates/

# copy nix-shell template to target directory
[no-cd]
copy-nixshell-template template_name target_directory:
  cp ~./_nixshell_templates/{{template_name}} {{target_directory}}/shell.nix
