name: build-review-automerge

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

jobs:
  build-review-automerge:
    uses: machinology/mach-shared-workflows/.github/workflows/build-review-automerge.yml@v1
    secrets: inherit
